

services:
  frontend:
    build: ./frontend
    container_name: new_quizapp_frontend
    restart: always
    ports:
      - "8080:80"
    environment:
      REACT_APP_API_URL: http://host.docker.internal:4422
